# Generated by Django 4.2.7 on 2024-02-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address_alter_user_city_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پستی'),
        ),
    ]
