# Generated by Django 3.2.6 on 2021-09-04 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210904_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 17, 1, 42, 871344, tzinfo=utc), verbose_name='تاریخ ثبت'),
        ),
    ]
