# Generated by Django 3.2.6 on 2021-09-04 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210904_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 18, 35, 45, 548882, tzinfo=utc), verbose_name='تاریخ ثبت'),
        ),
    ]
