# Generated by Django 3.2.6 on 2021-09-04 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 4, 18, 41, 9, 295366, tzinfo=utc), verbose_name='تاریخ ثبت'),
        ),
    ]
