# Generated by Django 3.2.6 on 2021-09-05 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210905_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 5, 5, 42, 42, 899669, tzinfo=utc), verbose_name='تاریخ ثبت'),
        ),
    ]
